AllCops:
  Exclude:
    - 'Guardfile'
    - 'bin/*'
    - 'db/*'
    - 'config/initializers/rails_admin.rb'
Layout/LineLength:
  Max: 250
Style/ClassAndModuleChildren:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Metrics/AbcSize:
  Exclude:
    - 'db/migrate/*'
Metrics/MethodLength:
  Exclude:
    - 'db/migrate/*'
Metrics/ClassLength:
  Max: 120
Metrics/ModuleLength:
  Max: 120
Metrics/BlockLength:
  Exclude:
    - 'config/routes.rb'
    - 'spec/models/*'
    - 'config/environments/*'